<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>./Assets/logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\logo.ico" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\SenkaSticker.Common\SenkaSticker.Common.csproj" />
    <ProjectReference Include="..\SenkaSticker.Controls\SenkaSticker.Controls.csproj" />
    <ProjectReference Include="..\SenkaSticker.Test\SenkaSticker.Test.csproj" />
  </ItemGroup>
</Project>
