<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
      <AvaloniaResource Include="Assets\Issue\Issue.png" />
      <AvaloniaResource Include="Assets\Issue\Test.png" />
      <AvaloniaResource Include="Assets\Issue\Requirement.png" />
      <AvaloniaResource Include="Assets\Issue\Star.png" />
      <AvaloniaResource Include="Assets\Issue\GrayStar.png" />
      <AvaloniaResource Include="Assets\Common\Ok.png" />
      <AvaloniaResource Include="Assets\Common\No.png" />
      <AvaloniaResource Include="Assets\Common\Sort.png" />
      <AvaloniaResource Include="Assets\Common\New.png" />
      <AvaloniaResource Include="Assets\Issue\Edit.png" />
      <AvaloniaResource Include="Assets\Message\Commit.png" />
      <AvaloniaResource Include="Assets\Message\Clear.png" />
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Caliburn.Micro.Avalonia" Version="5.0.181-beta" />
    <PackageReference Include="Caliburn.Micro.Core" Version="5.0.181-beta" />
    <PackageReference Include="Caliburn.Micro.Platform.Core" Version="5.0.181-beta" />
    <PackageReference Include="Avalonia.BuildServices" Version="0.0.31" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.FreeDesktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Native" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Remote.Protocol" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Skia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Win32" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.X11" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactions.Custom" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactions.DragAndDrop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactions.Draggable" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactions.Events" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactions.Reactive" Version="11.0.5" />
    <PackageReference Include="Avalonia.Xaml.Interactions.Responsive" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Interactivity" Version="$(AvaloniaVersion)" />
    <PackageReference Include="ColorTextBlock.Avalonia" Version="11.0.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
    <PackageReference Include="DialogHost.Avalonia" Version="0.7.7" />
    <PackageReference Include="Markdown.Avalonia.Tight" Version="11.0.2" />
    <PackageReference Include="MessageBox.Avalonia" Version="3.1.6" />
    <PackageReference Include="Semi.Avalonia" Version="11.0.1" />
    <PackageReference Include="Semi.Avalonia.ColorPicker" Version="11.0.1" />
    <PackageReference Include="Semi.Avalonia.DataGrid" Version="11.0.1.1" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\SenkaSticker.Common\SenkaSticker.Common.csproj" />
</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SenkaSticker.Build\SenkaSticker.Build.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    <ProjectReference Include="..\SenkaSticker.Database\SenkaSticker.Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Components\Parts\Views\ConfirmView.axaml.cs">
      <DependentUpon>ConfirmView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Components\PartViews\EmptyCustomControl.axaml.cs">
      <DependentUpon>EmptyCustomControl.axaml</DependentUpon>
    </Compile>
    <Compile Update="Components\PartViews\CollectionsTree.axaml.cs">
      <DependentUpon>CollectionsTree.axaml</DependentUpon>
    </Compile>
    <Compile Update="Components\PartViews\SeperateTimePicker.axaml.cs">
      <DependentUpon>SeperateTimePicker.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
