<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="CustomPanelTest\Views\DemoView.axaml.cs">
      <SubType>Code</SubType>
      <DependentUpon>%(Filename)</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
     <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SenkaSticker.Common\SenkaSticker.Common.csproj" />
    <ProjectReference Include="..\SenkaSticker.Controls\SenkaSticker.Controls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CustomPanelTest\Views\DefaultSenkaGridView.axaml">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

</Project>
